CREATE TABLE `tb_hotel_connectivity_setup` (
  `hotel_id` int NOT NULL COMMENT 'tb_hotel.id',
  `hotel_code` varchar(100) NOT NULL COMMENT 'tb_hotel.code',
  `hotel_name` varchar(100) NOT NULL COMMENT 'tb_hotel.name',
  `property_category` varchar(255) NOT NULL COMMENT 'ms_property_category.category_name',
  `hotel_brand` varchar(255) NULL COMMENT 'ms_brand.brand_name',
  `street_address` text NOT NULL COMMENT 'tb_hotel.street_address',
  `city` varchar(100) NOT NULL COMMENT 'tb_hotel.area',
  `province` varchar(255) NOT NULL COMMENT 'tb_hotel.region',
  `zip_code` varchar(255) NULL COMMENT 'tb_hotel.zip_code',
  `country` varchar(2) NOT NULL DEFAULT 'ID' COMMENT 'Statis value',
  `latitude` varchar(255) NULL COMMENT 'tb_hotel.latitude',
  `longitude` varchar(255) NULL COMMENT 'tb_hotel.longitude',
  `phone` varchar(255) NULL COMMENT 'tb_hotel.phone',
  `room_type_id` int NOT NULL COMMENT 'tb_hotel_room_type.id',
  `room_type_name` varchar(255) NOT NULL COMMENT 'tb_hotel_room_type.name',
  `room_capacity` int NOT NULL COMMENT 'tb_hotel_room_type.guest',
  `room_smoking` int NOT NULL COMMENT 'tb_hotel_room_type.smoking',
  `room_view` varchar(255) NULL COMMENT 'tb_hotel_room_type.view',
  `room_image_url` text NULL COMMENT 'tb_hotel_image.filename',
  `rate_plan_id` int NOT NULL COMMENT 'tb_hotel_rate_plan.id',
  `rate_plan_name` varchar(255) NOT NULL COMMENT 'tb_hotel_rate_plan.name',
  `breakfast_included` tinyint(1) NOT NULL COMMENT 'tb_hotel_rate_plan.food',
  `pay_at_hotel` tinyint(1) NOT NULL COMMENT 'tb_hotel_rate_plan.pay_at_hotel',
  `setup_status` tinyint(1) NOT NULL DEFAULT  0 COMMENT 'Kontrol internal (0=Invalid/Draft, 1=Valid/Live)',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`hotel_id`, `room_type_id`, `rate_plan_id`),
  INDEX `lookup_idx` (`hotel_code`, `room_type_id`, `rate_plan_id`),
  INDEX `status_active_idx` (`setup_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;